- name: install strongswan
  apt: name=strongswan

- name: put /etc/ipsec.conf
  template: src=ipsec.conf dest=/etc/ipsec.conf

- name: put /etc/ipsec.secrets
  template: src=ipsec.secrets dest=/etc/ipsec.secrets mode=0600

- name: start strongswan
  service: name=strongswan state=started enabled=yes
